/**
 * Init Command
 *
 * Story 3.1: `wos init` Command
 *
 * Initializes a new WorldOS server directory.
 */

import { Command, Flags, Args } from '@oclif/core';
import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Default wos.yaml content
 */
export function getDefaultConfig(name: string): string {
  return `# WorldOS Server Configuration
# Generated by wos init

# Server settings
server:
  name: ${name}
  logLevel: info

# MQTT broker settings
mqtt:
  host: localhost
  port: 1883
  # username: ''
  # password: ''

# Admin panel settings
admin:
  enabled: true
  port: 3000
  # username: admin
  # password: (set via wos config)

# Plugins configuration
plugins: {}

# Webhooks for event notifications
webhooks: []
`;
}

/**
 * Initialize a new WorldOS server directory
 */
export async function initServerDirectory(
  directory: string,
  options: { name?: string; force?: boolean } = {}
): Promise<{ created: string[]; skipped: string[] }> {
  const created: string[] = [];
  const skipped: string[] = [];

  // Create main directory
  await fs.mkdir(directory, { recursive: true });

  // Create plugins directory
  const pluginsDir = path.join(directory, 'plugins');
  try {
    await fs.mkdir(pluginsDir, { recursive: true });
    created.push('plugins/');
  } catch {
    skipped.push('plugins/');
  }

  // Create wos.yaml
  const configPath = path.join(directory, 'wos.yaml');
  const serverName = options.name ?? path.basename(directory);

  try {
    await fs.access(configPath);
    if (options.force) {
      await fs.writeFile(configPath, getDefaultConfig(serverName), 'utf-8');
      created.push('wos.yaml');
    } else {
      skipped.push('wos.yaml (already exists)');
    }
  } catch {
    await fs.writeFile(configPath, getDefaultConfig(serverName), 'utf-8');
    created.push('wos.yaml');
  }

  // Create .gitignore
  const gitignorePath = path.join(directory, '.gitignore');
  const gitignoreContent = `# WorldOS
node_modules/
*.log
.env
.env.local

# Plugin build artifacts
plugins/*/dist/
plugins/*/node_modules/

# OS files
.DS_Store
Thumbs.db
`;

  try {
    await fs.access(gitignorePath);
    if (options.force) {
      await fs.writeFile(gitignorePath, gitignoreContent, 'utf-8');
      created.push('.gitignore');
    } else {
      skipped.push('.gitignore (already exists)');
    }
  } catch {
    await fs.writeFile(gitignorePath, gitignoreContent, 'utf-8');
    created.push('.gitignore');
  }

  return { created, skipped };
}

/**
 * Check if a directory is a valid WorldOS server
 */
export async function isServerDirectory(directory: string): Promise<boolean> {
  try {
    const configPath = path.join(directory, 'wos.yaml');
    await fs.access(configPath);
    return true;
  } catch {
    return false;
  }
}

export default class Init extends Command {
  static override description = 'Initialize a new WorldOS server directory';

  static override examples = [
    '<%= config.bin %> init',
    '<%= config.bin %> init my-server',
    '<%= config.bin %> init ./servers/production --name prod-server',
    '<%= config.bin %> init --force',
  ];

  static override flags = {
    name: Flags.string({
      char: 'n',
      description: 'Server name (defaults to directory name)',
    }),
    force: Flags.boolean({
      char: 'f',
      description: 'Overwrite existing configuration files',
      default: false,
    }),
    json: Flags.boolean({
      description: 'Output in JSON format',
      default: false,
    }),
  };

  static override args = {
    directory: Args.string({
      description: 'Directory to initialize (defaults to current directory)',
      required: false,
    }),
  };

  public async run(): Promise<void> {
    const { args, flags } = await this.parse(Init);

    const directory = args.directory
      ? path.resolve(args.directory)
      : process.cwd();

    // Check if already initialized
    const isInitialized = await isServerDirectory(directory);
    if (isInitialized && !flags.force) {
      if (flags.json) {
        this.log(JSON.stringify({
          success: false,
          error: 'Directory is already a WorldOS server. Use --force to reinitialize.',
          directory,
        }));
      } else {
        this.warn('Directory is already a WorldOS server.');
        this.log('Use --force to reinitialize.');
      }
      return;
    }

    try {
      const result = await initServerDirectory(directory, {
        name: flags.name,
        force: flags.force,
      });

      if (flags.json) {
        this.log(JSON.stringify({
          success: true,
          directory,
          created: result.created,
          skipped: result.skipped,
        }));
      } else {
        this.log(`Initialized WorldOS server in ${directory}`);
        this.log('');

        if (result.created.length > 0) {
          this.log('Created:');
          for (const file of result.created) {
            this.log(`  + ${file}`);
          }
        }

        if (result.skipped.length > 0) {
          this.log('Skipped:');
          for (const file of result.skipped) {
            this.log(`  - ${file}`);
          }
        }

        this.log('');
        this.log('Next steps:');
        this.log('  1. Configure your MQTT broker in wos.yaml');
        this.log('  2. Add plugins with: wos add <plugin-path>');
        this.log('  3. Start the server with: wos start');
      }
    } catch (error) {
      if (flags.json) {
        this.log(JSON.stringify({
          success: false,
          error: (error as Error).message,
          directory,
        }));
      } else {
        this.error((error as Error).message);
      }
    }
  }
}
